FROM node:22-alpine AS build-stage

WORKDIR /app

COPY package*.json .

COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build


FROM node:22-alpine AS production-stage

WORKDIR /app

RUN npm install -g http-server

COPY --from=build-stage /app/dist /app/dist

EXPOSE 8080

CMD ["http-server", "/app/dist", "-p", "8080", "-c-1", "--proxy", "http://127.0.0.1:8080?"]
